version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3000:3000" 
    environment:
      MONGO_URI: mongodb://mongo:27017/booklibrary
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5500:5500"
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "127.0.0.1:27017:27017" 
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
